export { $lib } from "./lib.js";
export * from "./decorators.js";
export { $onEmit } from "./emitter.js";

// Export decorators for TypeSpec runtime
import {
  $resource,
  $requiredOneOf,
  $label,
  $kind,
  $options,
  $relation,
  $cardinality,
  $ui,
  $hint,
  $inputHint,
  $readonly,
  $computed,
  $createOnly,
  $filter,
  $view,
  $columns,
  $fields,
  $searchable,
  $sortable,
  $defaultSort,
  $clickAction,
  $selection,
  $namedFilters,
  $namedFilter,
  $action,
  $rowAction,
  $placement,
  $requiresSelection,
  $allowedWhen,
  $visibleWhen,
  $requiredWhen,
  $confirm,
  $dialog,
  $api,
  $match,
  $required,
  $min,
  $max,
} from "./decorators.js";

export const $decorators = {
  S: {
    resource: $resource,
    requiredOneOf: $requiredOneOf,
    label: $label,
    kind: $kind,
    options: $options,
    relation: $relation,
    cardinality: $cardinality,
    ui: $ui,
    hint: $hint,
    inputHint: $inputHint,
    readonly: $readonly,
    computed: $computed,
    createOnly: $createOnly,
    filter: $filter,
    view: $view,
    columns: $columns,
    fields: $fields,
    searchable: $searchable,
    sortable: $sortable,
    defaultSort: $defaultSort,
    clickAction: $clickAction,
    selection: $selection,
    namedFilters: $namedFilters,
    namedFilter: $namedFilter,
    action: $action,
    rowAction: $rowAction,
    placement: $placement,
    requiresSelection: $requiresSelection,
    allowedWhen: $allowedWhen,
    visibleWhen: $visibleWhen,
    requiredWhen: $requiredWhen,
    confirm: $confirm,
    dialog: $dialog,
    api: $api,
    match: $match,
    required: $required,
    min: $min,
    max: $max,
  },
};
