export { $lib } from "./lib.js";
export * from "./decorators.js";
export { $onEmit } from "./emitter.js";

// Export decorators for TypeSpec runtime
import {
  $resource,
  $label,
  $kind,
  $options,
  $relation,
  $ui,
  $readonly,
  $computed,
  $filter,
  $view,
  $columns,
  $fields,
  $searchable,
  $sortable,
  $defaultSort,
  $clickAction,
  $selection,
  $namedFilters,
  $namedFilter,
  $action,
  $rowAction,
  $requiresSelection,
  $allowedWhen,
  $confirm,
  $required,
  $minLength,
  $maxLength,
  $min,
  $max,
  $pattern,
  $minItems,
  $maxItems,
} from "./decorators.js";

export const $decorators = {
  Specloom: {
    resource: $resource,
    label: $label,
    kind: $kind,
    options: $options,
    relation: $relation,
    ui: $ui,
    readonly: $readonly,
    computed: $computed,
    filter: $filter,
    view: $view,
    columns: $columns,
    fields: $fields,
    searchable: $searchable,
    sortable: $sortable,
    defaultSort: $defaultSort,
    clickAction: $clickAction,
    selection: $selection,
    namedFilters: $namedFilters,
    namedFilter: $namedFilter,
    action: $action,
    rowAction: $rowAction,
    requiresSelection: $requiresSelection,
    allowedWhen: $allowedWhen,
    confirm: $confirm,
    required: $required,
    minLength: $minLength,
    maxLength: $maxLength,
    min: $min,
    max: $max,
    pattern: $pattern,
    minItems: $minItems,
    maxItems: $maxItems,
  },
};
